/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as MailIndexRouteImport } from './routes/mail/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as MailEmailIdRouteImport } from './routes/mail/$emailId'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices/$invoiceId'
import { Route as ApiReprocessRouteImport } from './routes/api/reprocess'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiWebhooksMailRouteImport } from './routes/api/webhooks/mail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailEmailIdRoute = MailEmailIdRouteImport.update({
  id: '/mail/$emailId',
  path: '/mail/$emailId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReprocessRoute = ApiReprocessRouteImport.update({
  id: '/api/reprocess',
  path: '/api/reprocess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMailRoute = ApiWebhooksMailRouteImport.update({
  id: '/api/webhooks/mail',
  path: '/api/webhooks/mail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reprocess': typeof ApiReprocessRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/mail/$emailId': typeof MailEmailIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/mail/': typeof MailIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/webhooks/mail': typeof ApiWebhooksMailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reprocess': typeof ApiReprocessRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/mail/$emailId': typeof MailEmailIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/invoices': typeof InvoicesIndexRoute
  '/mail': typeof MailIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/webhooks/mail': typeof ApiWebhooksMailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reprocess': typeof ApiReprocessRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/mail/$emailId': typeof MailEmailIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/mail/': typeof MailIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/webhooks/mail': typeof ApiWebhooksMailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/reprocess'
    | '/invoices/$invoiceId'
    | '/mail/$emailId'
    | '/tasks/$taskId'
    | '/invoices/'
    | '/mail/'
    | '/tasks/'
    | '/api/webhooks/mail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/reprocess'
    | '/invoices/$invoiceId'
    | '/mail/$emailId'
    | '/tasks/$taskId'
    | '/invoices'
    | '/mail'
    | '/tasks'
    | '/api/webhooks/mail'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/reprocess'
    | '/invoices/$invoiceId'
    | '/mail/$emailId'
    | '/tasks/$taskId'
    | '/invoices/'
    | '/mail/'
    | '/tasks/'
    | '/api/webhooks/mail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiReprocessRoute: typeof ApiReprocessRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  MailEmailIdRoute: typeof MailEmailIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  MailIndexRoute: typeof MailIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiWebhooksMailRoute: typeof ApiWebhooksMailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/': {
      id: '/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/$emailId': {
      id: '/mail/$emailId'
      path: '/mail/$emailId'
      fullPath: '/mail/$emailId'
      preLoaderRoute: typeof MailEmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reprocess': {
      id: '/api/reprocess'
      path: '/api/reprocess'
      fullPath: '/api/reprocess'
      preLoaderRoute: typeof ApiReprocessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mail': {
      id: '/api/webhooks/mail'
      path: '/api/webhooks/mail'
      fullPath: '/api/webhooks/mail'
      preLoaderRoute: typeof ApiWebhooksMailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiReprocessRoute: ApiReprocessRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  MailEmailIdRoute: MailEmailIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  MailIndexRoute: MailIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiWebhooksMailRoute: ApiWebhooksMailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
